# name: auto merge

# on:
#   workflow_run:
#     types:
#       - completed
#     workflows:
#       - 'ci cd'

# jobs:
#   merge-me:
#     runs-on: ubuntu-latest
#     name: auto merge dependabot PRs
#     steps:
#       - name: auto merge
#         if: ${{ github.event.workflow_run.conclusion == 'success' }}
#         uses: ridedott/merge-me-action@v2
#         with:
#           # This must be used as GitHub Actions token does not support pushing
#           # to protected branches.
#           GITHUB_TOKEN: ${{ secrets.ORG_LEVEL_PM_TOKEN }}
#           PRESET: DEPENDABOT_MINOR
